#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Sep 29 10:59:03 IST 2026
# SW Build 6299465 on Fri Nov 14 12:34:56 MST 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
export SIM_VER_XSIM=2025.2
export GCC_VER_XSIM=9.3.0

# catch pipeline exit status
set -Eeuo pipefail
# simulate design
echo "xsim tb_register_file_behav -key {Behavioral:sim_1:Functional:tb_register_file} -tclbatch tb_register_file.tcl -view /home/haricious/haricious/RTL/rtl-based-projects-phase-1/p1_projects/05_Register_FIle/vivado_file/tb_register_file_behav.wcfg -log simulate.log"
xsim tb_register_file_behav -key {Behavioral:sim_1:Functional:tb_register_file} -tclbatch tb_register_file.tcl -view /home/haricious/haricious/RTL/rtl-based-projects-phase-1/p1_projects/05_Register_FIle/vivado_file/tb_register_file_behav.wcfg -log simulate.log

